services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    profiles: [whoami]
    networks:
      - reverse-proxy
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.${DOMAIN:?}`)
      traefik.http.routers.whoami.entryPoints: websecure
    restart: unless-stopped
