services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - reverse-proxy
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.${DOMAIN:?}`)
      traefik.http.routers.whoami.entryPoints: websecure
      traefik.http.routers.whoami.middlewares: crowdsec-bouncer@docker
    restart: unless-stopped

networks:
  reverse-proxy:
    name: reverse-proxy
    external: true
