services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    profiles: [streaming]
    environment:
      TZ: ${TZ:?}
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.flaresolverr.rule: Host(`flaresolverr.${DOMAIN:?}`)
      traefik.http.routers.flaresolverr.entryPoints: websecure
      traefik.http.routers.flaresolverr.middlewares: ip-allowlist@docker
    restart: unless-stopped
