services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    env_file:
      - ../../.env
    environment:
      EULA: TRUE
      MAX_MEMORY: 4G
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ${APP_DATA_PATH}/games/minecraft
        target: /data
    networks:
      - minecraft
    ports:
      - 25565:25565
    restart: unless-stopped

networks:
  minecraft:
