services:
  mealie:
    image: hkotel/mealie
    container_name: mealie
    profiles:
      - mealie
    environment:
      BASE_URL: "https://mealie.${DOMAIN:?}"
      OIDC_AUTH_ENABLED: true
      OIDC_CONFIGURATION_URL: "https://pocketid.${DOMAIN:?}/.well-known/openid-configuration"
      OIDC_CLIENT_ID: ${MEALIE_OIDC_CLIENT_ID:?}
      OIDC_CLIENT_SECRET: ${MEALIE_OIDC_CLIENT_SECRET:?}
      OIDC_AUTO_REDIRECT: true
      OIDC_REMEMBER_ME: true
      OIDC_ADMIN_GROUP: "mealie_admins"
      OIDC_PROVIDER_NAME: Land of Oz

      # Default Recipe Settings
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "true"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "false"
      RECIPE_DISABLE_AMOUNT: "false"

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    # ports:
    #   - 9925:80
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/mealie
        target: /app/data
    labels:
      com.centurylinklabs.watchtower.enable: true
      docker-volume-backup.stop-during-backup: mealie
      traefik.enable: true
      traefik.http.routers.mealie.rule: Host(`mealie.${DOMAIN:?}`)
      traefik.http.routers.mealie.entrypoints: websecure
    networks:
      - mealie
    restart: unless-stopped

  mealie-backup:
    image: offen/docker-volume-backup:v2
    container_name: mealie-backup
    profiles:
      - backup
      - mealie
    environment:
      EXEC_LABEL: mealie
      BACKUP_STOP_DURING_BACKUP_LABEL: mealie
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/mealie
        target: /backup/mealie
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/mealie
        target: /archive
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  mealie:
    name: mealie
