services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    profiles:
      - readarr
      - streaming
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/readarr
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 8787:8787
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.readarr.rule: Host(`readarr.${DOMAIN:?}`)
      traefik.http.routers.readarr.entryPoints: websecure
      traefik.http.routers.readarr.middlewares: ip-allowlist@docker
    depends_on:
      - qbittorrent
    restart: unless-stopped

  readarr-backup:
    image: offen/docker-volume-backup:v2
    container_name: readarr-backup
    profiles:
      - backup
      - readarr
      - streaming
    environment:
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/readarr
        target: /backup/readarr
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/readarr
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
