services:
  sonarr: &sonarr
    image: linuxserver/sonarr
    container_name: sonarr
    profiles:
      - sonarr
      - streaming
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/sonarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 8989:8989
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN:?}`)
      traefik.http.routers.sonarr.entryPoints: websecure
      traefik.http.routers.sonarr.middlewares: ip-allowlist@docker
    depends_on:
      - qbittorrent
    restart: unless-stopped

  sonarr-4k:
    <<: *sonarr
    container_name: sonarr-4k
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/sonarr-4k
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr-4k
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 8990:8989
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.sonarr-4k.rule: Host(`sonarr4k.${DOMAIN:?}`)
      traefik.http.routers.sonarr-4k.entryPoints: websecure
      traefik.http.routers.sonarr-4k.middlewares: ip-allowlist@docker

  sonarr-anime:
    <<: *sonarr
    container_name: sonarr-anime
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/sonarr-anime
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr-anime
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 8991:8989
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.sonarr-anime.rule: Host(`sonarr-anime.${DOMAIN:?}`)
      traefik.http.routers.sonarr-anime.entryPoints: websecure
      traefik.http.routers.sonarr-anime.middlewares: ip-allowlist@docker

  sonarr-backup:
    image: offen/docker-volume-backup:v2
    container_name: sonarr-backup
    profiles:
      - backup
      - sonarr
      - streaming
    environment:
      EXEC_LABEL: sonarr
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr
        target: /backup/sonarr
        read_only: true
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr-4k
        target: /backup/sonarr
        read_only: true
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr-anime
        target: /backup/sonarr
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/sonarr
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
