services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    profiles: [streaming]
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/sonarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 8989:8989
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN:?}`)
      traefik.http.routers.sonarr.entryPoints: websecure
      traefik.http.routers.sonarr.middlewares: ip-allowlist@docker
    depends_on:
      - qbittorrent
    restart: unless-stopped

  sonarr-backup:
    image: offen/docker-volume-backup:latest
    container_name: sonarr-backup
    profiles: [streaming]
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr
        target: /backup/sonarr
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/sonarr
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
