services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    profiles: [filebrowser]
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/filebrowser/database
        target: /database
      - type: bind
        source: ${APP_DATA_PATH:?}/filebrowser/config/settings.json
        target: /.filebrowser.json
      - type: bind
        source: ${USER_DATA_PATH:?}/files
        target: /srv
    ports:
      - 26713:80
    networks:
      - filebrowser
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.filebrowser.rule: Host(`filebrowser.${DOMAIN:?}`)
      traefik.http.routers.filebrowser.entryPoints: websecure
      # traefik.http.routers.filebrowser.middlewares: ip-allowlist@docker
    restart: unless-stopped

networks:
  filebrowser:
    name: filebrowser
