include:
  - zigbee2mqtt/compose.yaml

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    profiles:
      - mqtt
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/mosquitto
        target: /mosquitto
    networks:
      - mqtt
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  mosquitto-backup:
    image: offen/docker-volume-backup:v2
    container_name: mosquitto-backup
    profiles:
      - backup
      - mqtt
    environment:
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/mosquitto
        target: /backup/mosquitto
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/mosquitto
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  mqtt:
    name: mqtt
