services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker
    container_name: speedtest-tracker
    profiles: [speedtest-tracker]
    environment:
      TZ: Etc/UTC
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      DISPLAY_TIMEZONE: ${TZ:?}
      # APP_DEBUG: true
      APP_KEY: ${SPEEDTEST_TRACKER_APP_KEY:?}
      DB_CONNECTION: pgsql
      DB_HOST: speedtest-db
      DB_PORT: 5432
      DB_DATABASE: ${SPEEDTEST_TRACKER_DB_DATABASE:?}
      DB_USERNAME: ${SPEEDTEST_TRACKER_DB_USERNAME:?}
      DB_PASSWORD: ${SPEEDTEST_TRACKER_DB_PASSWORD:?}
      SPEEDTEST_SCHEDULE: "0 */1 * * *"
      SPEEDTEST_SERVERS: ${SPEEDTEST_TRACKER_SERVERS:?}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/speedtest-tracker/config
        target: /config
    networks:
      - speedtest-tracker
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.speedtest.rule: Host(`speedtest.${DOMAIN:?}`)
      traefik.http.routers.speedtest.entryPoints: websecure
      traefik.http.routers.speedtest.middlewares: ip-allowlist@docker
      traefik.http.services.speedtest.loadbalancer.server.port: 80
    depends_on:
      - speedtest-db
    restart: unless-stopped

  speedtest-db:
    image: postgres:15
    container_name: speedtest-db
    profiles: [speedtest-tracker]
    environment:
      POSTGRES_DB: ${SPEEDTEST_TRACKER_DB_DATABASE:?}
      POSTGRES_USER: ${SPEEDTEST_TRACKER_DB_USERNAME:?}
      POSTGRES_PASSWORD: ${SPEEDTEST_TRACKER_DB_PASSWORD:?}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/speedtest-tracker/data
        target: /var/lib/postgresql/data
    networks:
      - speedtest-tracker
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  speedtest-tracker-backup:
    image: offen/docker-volume-backup:v2
    container_name: speedtest-tracker-backup
    profiles: [speedtest-tracker]
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/speedtest-tracker
        target: /backup/speedtest-tracker
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/speedtest-tracker
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  speedtest-tracker:
    name: speedtest-tracker
