include:
  - esphome/compose.yaml

services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    profiles:
      - home-assistant
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
    volumes:
      - type: bind
        source: /run/dbus
        target: /run/dbus
        read_only: true
      - type: bind
        source: ${APP_DATA_PATH:?}/home-assistant
        target: /config
    networks:
      - home-assistant
      - mqtt
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.home-assistant.rule: Host(`home.${DOMAIN:?}`)
      traefik.http.routers.home-assistant.entryPoints: websecure
      traefik.http.routers.home-assistant.middlewares: ip-allowlist@docker
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123
    restart: unless-stopped

  home-assistant-backup:
    image: offen/docker-volume-backup:v2
    container_name: home-assistant-backup
    profiles:
      - backup
      - home-assistant
    environment:
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/home-assistant
        target: /backup/home-assistant
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/home-assistant
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  home-assistant:
    name: home-assistant
