services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    profiles:
      - home-assistant
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
    volumes:
      - type: bind
        source: /run/dbus
        target: /run/dbus
        read_only: true
      - type: bind
        source: ${APP_DATA_PATH:?}/homeassistant
        target: /config
    network_mode: host
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.homeassistant.rule: Host(`homeassistant.${DOMAIN:?}`)
      traefik.http.routers.homeassistant.entryPoints: websecure
      traefik.http.routers.homeassistant.middlewares: ip-allowlist@docker
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
    restart: unless-stopped

  homeassistant-backup:
    image: offen/docker-volume-backup:v2
    container_name: homeassistant-backup
    profiles:
      - backup
      - home-assistant
    environment:
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/homeassistant
        target: /backup/homeassistant
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/homeassistant
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
