services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    profiles: [streaming]
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
      RECYCLARR_CREATE_CONFIG: true
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/recyclarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/recyclarr
        target: /config
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
