services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    profiles: [streaming]
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
      RECYCLARR_CREATE_CONFIG: true
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/recyclarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/recyclarr
        target: /config
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  recyclarr-backup:
    image: offen/docker-volume-backup:latest
    container_name: recyclarr-backup
    profiles: [streaming]
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/recyclarr
        target: /backup/recyclarr
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/recyclarr
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
