services:
  microbin:
    image: danielszabo99/microbin:latest
    container_name: microbin
    profiles:
      - microbin
    environment:
      # MICROBIN_BASIC_AUTH_USERNAME:
      # MICROBIN_BASIC_AUTH_PASSWORD:
      MICROBIN_ADMIN_USERNAME: ${MICROBIN_ADMIN_USERNAME:?}
      MICROBIN_ADMIN_PASSWORD: ${MICROBIN_ADMIN_PASSWORD:?}
      MICROBIN_EDITABLE: true
      # MICROBIN_FOOTER_TEXT:
      MICROBIN_HIDE_FOOTER: false
      MICROBIN_HIDE_HEADER: false
      MICROBIN_HIDE_LOGO: false
      MICROBIN_NO_LISTING: false
      MICROBIN_HIGHLIGHTSYNTAX: true
      MICROBIN_BIND: 0.0.0.0
      MICROBIN_PRIVATE: true
      MICROBIN_PURE_HTML: false
      MICROBIN_DATA_DIR: microbin_data
      MICROBIN_JSON_DB: false
      MICROBIN_PUBLIC_PATH: https://microbin.${DOMAIN:?}/
      # MICROBIN_SHORT_PATH:
      MICROBIN_READONLY: false
      MICROBIN_SHOW_READ_STATS: true
      # MICROBIN_TITLE:
      MICROBIN_THREADS: 1
      MICROBIN_GC_DAYS: 180
      MICROBIN_ENABLE_BURN_AFTER: true
      MICROBIN_DEFAULT_BURN_AFTER: 0
      MICROBIN_WIDE: false
      MICROBIN_QR: true
      MICROBIN_ETERNAL_PASTA: false
      MICROBIN_ENABLE_READONLY: true
      MICROBIN_DEFAULT_EXPIRY: 1week
      MICROBIN_NO_FILE_UPLOAD: true
      # MICROBIN_CUSTOM_CSS:
      MICROBIN_HASH_IDS: false
      MICROBIN_ENCRYPTION_CLIENT_SIDE: true
      MICROBIN_ENCRYPTION_SERVER_SIDE: true
      MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: 256
      MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB: 2048
    volumes:
      - type: bind
        source: ${USER_DATA_PATH:?}/microbin
        target: /app/microbin_data
    networks:
      - microbin
    labels:
      com.centurylinklabs.watchtower.enable: true
      docker-volume-backup.stop-during-backup: microbin
      traefik.enable: true
      traefik.http.routers.microbin.rule: Host(`microbin.${DOMAIN:?}`)
      traefik.http.routers.microbin.entryPoints: websecure
    restart: unless-stopped

  microbin-backup:
    image: offen/docker-volume-backup:v2
    container_name: microbin-backup
    profiles:
      - backup
      - microbin
    environment:
      EXEC_LABEL: microbin
      BACKUP_STOP_DURING_BACKUP_LABEL: microbin
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${USER_DATA_PATH:?}/microbin
        target: /backup/microbin
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/microbin
        target: /archive
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  microbin:
    name: microbin
