services:
  microbin:
    image: danielszabo99/microbin:latest
    container_name: microbin
    env_file:
      - ../.env
      - .env
    environment:
      # MICROBIN_BASIC_AUTH_USERNAME:
      # MICROBIN_BASIC_AUTH_PASSWORD:
      MICROBIN_EDITABLE: true
      # MICROBIN_FOOTER_TEXT:
      MICROBIN_HIDE_FOOTER: false
      MICROBIN_HIDE_HEADER: false
      MICROBIN_HIDE_LOGO: false
      MICROBIN_NO_LISTING: false
      MICROBIN_HIGHLIGHTSYNTAX: true
      MICROBIN_BIND: "0.0.0.0"
      MICROBIN_PRIVATE: true
      MICROBIN_PURE_HTML: false
      MICROBIN_DATA_DIR: "microbin_data"
      MICROBIN_JSON_DB: false
      MICROBIN_PUBLIC_PATH: "https://microbin.${DOMAIN}/"
      # MICROBIN_SHORT_PATH:
      MICROBIN_READONLY: false
      MICROBIN_SHOW_READ_STATS: true
      # MICROBIN_TITLE:
      MICROBIN_THREADS: 1
      MICROBIN_GC_DAYS: 180
      MICROBIN_ENABLE_BURN_AFTER: true
      MICROBIN_DEFAULT_BURN_AFTER: 0
      MICROBIN_WIDE: false
      MICROBIN_QR: true
      MICROBIN_ETERNAL_PASTA: false
      MICROBIN_ENABLE_READONLY: true
      MICROBIN_DEFAULT_EXPIRY: 1week
      MICROBIN_NO_FILE_UPLOAD: true
      # MICROBIN_CUSTOM_CSS:
      MICROBIN_HASH_IDS: false
      MICROBIN_ENCRYPTION_CLIENT_SIDE: true
      MICROBIN_ENCRYPTION_SERVER_SIDE: true
      MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: 256
      MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB: 2048
    volumes:
      - type: bind
        source: ${USER_DATA_PATH}/microbin
        target: /app/microbin_data
    networks:
      - microbin
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.microbin.rule: Host(`microbin.${DOMAIN}`)
      traefik.http.routers.microbin.entryPoints: websecure
    restart: unless-stopped

networks:
  microbin:
