services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    profiles:
      - homepage
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/homepage
        target: /app/config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/homepage
        target: /app/config
    networks:
      - homepage
      - watchtower
      - immich
      # - photoprism
      - streaming
      - mealie
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`${DOMAIN:?}`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.middlewares: ip-allowlist@docker
    restart: unless-stopped

  homepage-backup:
    image: offen/docker-volume-backup:v2
    container_name: homepage-backup
    profiles:
      - backup
      - homepage
    environment:
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/homepage
        target: /backup/config
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/homepage
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  homepage:
    name: homepage
