services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - ../.env
    volumes:
      - type: bind
        source: ${APP_LOG_PATH}/homepage
        target: /app/config/logs
      - type: bind
        source: ${APP_DATA_PATH}/homepage
        target: /app/config
    networks:
      - homepage
      - watchtower
      - immich
      - photoprism
      - streaming
      - mealie
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`${DOMAIN}`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.middlewares: authelia@file
    restart: unless-stopped

networks:
  homepage:
  watchtower:
    external: true
  immich:
    external: true
  photoprism:
    external: true
  streaming:
    external: true
  mealie:
    external: true
