services:
  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    profiles:
      - jellyseerr
      - streaming
    environment:
      TZ: ${TZ:?}
      LOG_LEVEL: debug
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/jellyseerr
        target: /app/config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/jellyseerr
        target: /app/config
    # ports:
    #   - 5055:5055
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      docker-volume-backup.stop-during-backup: jellyseerr
      traefik.enable: true
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.${DOMAIN:?}`)
      traefik.http.routers.jellyseerr.entryPoints: websecure
    depends_on:
      - jellyfin
      - radarr
      - sonarr
    restart: unless-stopped

  jellyseerr-backup:
    image: offen/docker-volume-backup:v2
    container_name: jellyseerr-backup
    profiles:
      - backup
      - jellyseerr
      - streaming
    environment:
      EXEC_LABEL: jellyseerr
      BACKUP_STOP_DURING_BACKUP_LABEL: jellyseerr
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/jellyseerr
        target: /backup/jellyseerr
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/jellyseerr
        target: /archive
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
