services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    env_file:
      - ../.env
      - .env
    environment:
      DB_HOSTNAME: "immich-postgres"
      REDIS_HOSTNAME: "immich-redis"
    volumes:
      - type: bind
        source: ${USER_DATA_PATH}/photos/immich
        target: /usr/src/app/upload
    command: [ "start.sh", "immich" ]
    networks:
      - immich
    # ports:
    #   - 2283:3001
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.immich.rule: Host(`immich.${DOMAIN}`)
      traefik.http.routers.immich.entrypoints: websecure
    depends_on:
      - immich-redis
      - immich-postgres
    restart: unless-stopped

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:release
    env_file:
      - ../.env
      - .env
    environment:
      DB_HOSTNAME: "immich-postgres"
      REDIS_HOSTNAME: "immich-redis"
    devices:
      # hardware acceleration
      - /dev/dri:/dev/dri
    volumes:
      - type: bind
        source: ${USER_DATA_PATH}/photos/immich
        target: /usr/src/app/upload
    command: [ "start.sh", "microservices" ]
    networks:
      - immich
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - immich-redis
      - immich-postgres
    restart: unless-stopped

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-machine-learning
    env_file:
      - ../.env
    volumes:
      - type: bind
        source: ${APP_DATA_PATH}/immich/ml
        target: /cache
    networks:
      - immich
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  immich-redis:
    image: redis:6.2-alpine
    container_name: immich-redis
    networks:
      - immich
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    container_name: immich-postgres
    env_file:
      - ../.env
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH}/immich/database
        target: /var/lib/postgresql/data
    networks:
      - immich
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  immich:
