services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    env_file:
      - ../.env
      - .env
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}
      PAPERLESS_OCR_LANGUAGES: "heb rus"
      PAPERLESS_URL: https://paperless.${DOMAIN}
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_OCR_LANGUAGE: heb
      # Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
      #PAPERLESS_FORCE_SCRIPT_NAME: /PATHPREFIX
      #PAPERLESS_STATIC_URL: /PATHPREFIX/static/ # trailing slash required
    volumes:
      - type: bind
        source: ${APP_DATA_PATH}/paperless/data
        target: /usr/src/paperless/data
      - type: bind
        source: ${USER_DATA_PATH}/documents/media
        target: /usr/src/paperless/media
      - type: bind
        source: ${USER_DATA_PATH}/documents/export
        target: /usr/src/paperless/export
      - type: bind
        source: ${USER_DATA_PATH}/documents/consume
        target: /usr/src/paperless/consume
    healthcheck:
      test:
        ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - paperless-ngx
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.paperless-ngx.rule: Host(`paperless.${DOMAIN}`)
      traefik.http.routers.paperless-ngx.entryPoints: websecure
      traefik.http.routers.paperless-ngx.middlewares: authelia@file
    depends_on:
      - paperless-redis
    restart: unless-stopped

  paperless-redis:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    volumes:
      - type: bind
        source: ${APP_DATA_PATH}/paperless/cache
        target: /data
    networks:
      - paperless-ngx
    restart: unless-stopped

networks:
  paperless-ngx:
