services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-server
    profiles: [satisfactory]
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      STEAMBETA: false
      MAXPLAYERS: 8
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/satisfactory
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}/games/satisfactory
        target: /config/saved
    networks:
      - satisfactory
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    restart: unless-stopped

  satisfactory-backup:
    image: offen/docker-volume-backup:v2
    container_name: satisfactory-backup
    profiles: [satisfactory]
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/satisfactory
        target: /backup/config
        read_only: true
      - type: bind
        source: ${USER_DATA_PATH:?}/games/satisfactory
        target: /backup/saved
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/satisfactory
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  satisfactory:
    name: satisfactory
