services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-server
    profiles:
      - game
      - satisfactory
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      STEAMBETA: false
      MAXPLAYERS: 4
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/satisfactory
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}/games/satisfactory
        target: /config/saved
    networks:
      - satisfactory
    ports:
      - 8777:7777/tcp
      - 8777:7777/udp
      - 8888:8888/tcp
    restart: unless-stopped

  satisfactory-backup:
    image: offen/docker-volume-backup:v2
    container_name: satisfactory-backup
    profiles:
      - backup
      - game
      - satisfactory
    environment:
      EXEC_LABEL: satisfactory-server
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/satisfactory
        target: /backup/config
        read_only: true
      - type: bind
        source: ${USER_DATA_PATH:?}/games/satisfactory
        target: /backup/saved
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/satisfactory
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  satisfactory:
    name: satisfactory
