services:
  omnibot:
    image: omnibot
    container_name: omnibot
    profiles: [omnibot]
    environment:
      CLIENT_ID: ${OMNIBOT_CLIENT_ID:?}
      DISCORD_TOKEN: ${OMNIBOT_DISCORD_TOKEN:?}
      GEMINI_API_KEY: ${OMNIBOT_GEMINI_API_KEY:?}
      DATA_PATH: /omnibot
      GUILD_ID: ${OMNIBOT_GUILD_ID:?}
      CHANNEL_ID: ${OMNIBOT_CHANNEL_ID:?}
    volumes:
      - type: bind
        source: ${USER_DATA_PATH:?}/omnibot
        target: /omnibot
        read_only: true
    networks:
      - omnibot
    restart: unless-stopped

networks:
  omnibot:
    name: omnibot
