services:
  omnibot:
    image: omnibot
    container_name: omnibot
    env_file:
      - .env
      - ../.env
    environment:
      CLIENT_ID: ${CLIENT_ID:?}
      DISCORD_TOKEN: ${DISCORD_TOKEN:?}
      DATA_PATH: /omnibot
      GUILD_ID: ${GUILD_ID:?}
      CHANNEL_ID: ${CHANNEL_ID:?}
    volumes:
      - type: bind
        source: ${USER_DATA_PATH:?}/omnibot
        target: /omnibot
        read_only: true
    networks:
      - omnibot
    restart: unless-stopped

networks:
  omnibot:
    name: omnibot
