services:
  omnibot:
    image: omnibot
    container_name: omnibot
    env_file:
      - ../.env
      - .env
    environment:
      DATA_PATH: "/omnibot"
    volumes:
      - type: bind
        source: ${USER_DATA_PATH}/omnibot
        target: /omnibot
        read_only: true
    networks:
      - omnibot
    restart: unless-stopped

networks:
  omnibot:
