services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    profiles:
      - calibre-web
      - streaming
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      HARDCOVER_TOKEN: ${CALIBRE_WEB_HARDCOVER_TOKEN:?}
      NETWORK_SHARE_MODE: true
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/calibre/config
        target: /config
      - type: bind
        source: ${APP_DATA_PATH:?}/calibre/ingest
        target: /cwa-book-ingest
      - type: bind
        source: ${USER_DATA_PATH:?}/calibre
        target: /calibre-library
    # ports:
    #   - 8083:8083
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      docker-volume-backup.stop-during-backup: calibre-web
      traefik.enable: true
      traefik.http.routers.calibre.rule: Host(`calibre.${DOMAIN:?}`)
      traefik.http.routers.calibre.entryPoints: websecure
    restart: unless-stopped

  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:dev
    container_name: calibre-web-automated-book-downloader
    profiles:
      - calibre-web
      - streaming
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      PRIORITIZE_WELIB: true
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/calibre/ingest
        target: /cwa-book-ingest
    # ports:
    #   - 8084:8084
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.calibre-downloader.rule: Host(`calibre-downloader.${DOMAIN:?}`)
      traefik.http.routers.calibre-downloader.entryPoints: websecure
    restart: unless-stopped

  calibre-web-backup:
    image: offen/docker-volume-backup:v2
    container_name: calibre-web-backup
    profiles:
      - backup
      - calibre-web
      - streaming
    environment:
      EXEC_LABEL: calibre-web
      BACKUP_STOP_DURING_BACKUP_LABEL: calibre-web
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/calibre
        target: /backup/calibre
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/calibre
        target: /archive
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
