services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    profiles: [streaming]
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/jellyfin
        target: /config/log
      - type: bind
        source: ${APP_DATA_PATH:?}/jellyfin
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /media
    ports:
      - 8096:8096
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.${DOMAIN:?}`)
      traefik.http.routers.jellyfin.entryPoints: websecure
    restart: unless-stopped

  jellyfin-backup:
    image: offen/docker-volume-backup:v2
    container_name: jellyfin-backup
    profiles: [streaming]
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/jellyfin
        target: /backup/jellyfin
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/jellyfin
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
