include:
  - autobrr/compose.yaml
  - bazarr/compose.yaml
  - calibre-web/compose.yaml
  - ersatztv/compose.yaml
  - flaresolverr/compose.yaml
  - janitorr/compose.yaml
  - jellyfin/compose.yaml
  - jellyseerr/compose.yaml
  - lidarr/compose.yaml
  - navidrome/compose.yaml
  - prowlarr/compose.yaml
  - qbittorrent/compose.yaml
  - radarr/compose.yaml
  - readarr/compose.yaml
  - recyclarr/compose.yaml
  - sonarr/compose.yaml

networks:
  streaming:
    name: streaming
