services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    profiles:
      - adguardhome
      - dns
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/adguardhome/conf
        target: /opt/adguardhome/conf
      - type: bind
        source: ${APP_DATA_PATH:?}/adguardhome/work
        target: /opt/adguardhome/work
    ports:
      - ${HOST_IP:?}:53:53/tcp # dns
      - ${HOST_IP:?}:53:53/udp # dns
      # - 67:67/udp                 # dhcp
      # - 68:68/tcp                 # dhcp
      # - 68:68/udp                 # dhcp
      - 3000:3000/tcp # web setup
      # - 853:853/tcp               # dns over tls
      # - 784:784/udp               # dns over quic
      # - 853:853/udp               # dns over quic
      # - 8853:8853/udp             # dns over quic
      # - 5443:5443/tcp             # dnscrypt
      # - 5443:5443/udp             # dnscrypt
    networks:
      - adguardhome
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.adguardhome.rule: Host(`adguard.${DOMAIN:?}`)
      traefik.http.routers.adguardhome.entryPoints: websecure
      traefik.http.routers.adguardhome.middlewares: ip-allowlist@docker
      traefik.http.services.adguardhome.loadbalancer.server.port: 80
    restart: unless-stopped

  adguardhome-backup:
    image: offen/docker-volume-backup:v2
    container_name: adguardhome-backup
    profiles:
      - adguardhome
      - backup
      - dns
    environment:
      EXEC_LABEL: adguardhome
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/adguardhome
        target: /backup/adguardhome
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/adguardhome
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  adguardhome:
    name: adguardhome
