services:
  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio
    profiles:
      - factorio
      - game
    environment:
      SAVE_NAME: _default
      GENERATE_NEW_SAVE: true
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/factorio
        target: /factorio
      - type: bind
        source: ${USER_DATA_PATH:?}/games/factorio/saves
        target: /factorio/saves
      - type: bind
        source: ${USER_DATA_PATH:?}/games/factorio/mods
        target: /factorio/mods
    networks:
      - factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    restart: unless-stopped

  factorio-backup:
    image: offen/docker-volume-backup:v2
    container_name: factorio-backup
    profiles:
      - backup
      - factorio
      - game
    environment:
      EXEC_LABEL: factorio
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/factorio
        target: /backup/factorio
        read_only: true
      - type: bind
        source: ${USER_DATA_PATH:?}/games/factorio/saves
        target: /backup/saves
        read_only: true
      - type: bind
        source: ${USER_DATA_PATH:?}/games/factorio/mods
        target: /backup/mods
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/factorio
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  factorio:
    name: factorio
