services:
  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio
    env_file:
      - ../../.env
    volumes:
      - type: bind
        source: ${APP_DATA_PATH}/factorio
        target: /factorio
    networks:
      - factorio
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp

networks:
  factorio:
