services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    profiles:
      - prowlarr
      - streaming
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/prowlarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/prowlarr
        target: /config
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.${DOMAIN:?}`)
      traefik.http.routers.prowlarr.entryPoints: websecure
      traefik.http.routers.prowlarr.middlewares: ip-allowlist@docker
    depends_on:
      - radarr
      - sonarr
      - readarr
    restart: unless-stopped

  prowlarr-backup:
    image: offen/docker-volume-backup:v2
    container_name: prowlarr-backup
    profiles:
      - backup
      - prowlarr
      - streaming
    environment:
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/prowlarr
        target: /backup/prowlarr
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/prowlarr
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
