services:
  radarr: &radarr
    image: linuxserver/radarr
    container_name: radarr
    profiles:
      - radarr
      - streaming
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/radarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/radarr
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 7878:7878
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.${DOMAIN:?}`)
      traefik.http.routers.radarr.entryPoints: websecure
      traefik.http.routers.radarr.middlewares: ip-allowlist@docker
    depends_on:
      - qbittorrent
    restart: unless-stopped

  radarr-4k:
    <<: *radarr
    container_name: radarr-4k
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/radarr-4k
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/radarr-4k
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    # ports:
    #   - 7879:7878
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.radarr-4k.rule: Host(`radarr4k.${DOMAIN:?}`)
      traefik.http.routers.radarr-4k.entryPoints: websecure
      traefik.http.routers.radarr-4k.middlewares: ip-allowlist@docker

  radarr-backup:
    image: offen/docker-volume-backup:v2
    container_name: radarr-backup
    profiles:
      - backup
      - radarr
      - streaming
    environment:
      EXEC_LABEL: radarr
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/radarr
        target: /backup/radarr
        read_only: true
      - type: bind
        source: ${APP_DATA_PATH:?}/radarr-4k
        target: /backup/radarr-4k
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/radarr
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
