services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    profiles:
      - stirling-pdf
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/stirling-pdf
        target: /configs
    networks:
      - stirling-pdf
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.stirling-pdf.rule: Host(`pdf.${DOMAIN:?}`)
      traefik.http.routers.stirling-pdf.entryPoints: websecure
    restart: unless-stopped

  stirling-pdf-backup:
    image: offen/docker-volume-backup:v2
    container_name: stirling-pdf-backup
    profiles:
      - backup
      - stirling-pdf
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/stirling-pdf
        target: /backup/stirling-pdf
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/stirling-pdf
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  stirling-pdf:
    name: stirling-pdf
