services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      WG_HOST: vpn.${DOMAIN:?}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/wg-easy
        target: /etc/wireguard
    ports:
      - 51820:51820/udp
    networks:
      - wireguard
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.wireguard.rule: Host(`vpn.${DOMAIN:?}`)
      traefik.http.routers.wireguard.entryPoints: websecure
      traefik.http.routers.wireguard.middlewares: ip-whitelist@docker
      traefik.http.services.wireguard.loadbalancer.server.port: 51821
    restart: unless-stopped

networks:
  wireguard:
    name: wireguard
