services:
  monica:
    image: monica
    container_name: monica
    profiles: [monica]
    environment:
      APP_KEY: ${MONICA_APP_KEY:?}
      APP_ENV: production
      DB_HOST: monica-db
      DB_USERNAME: ${MONICA_DB_USERNAME:?}
      DB_PASSWORD: ${MONICA_DB_PASSWORD:?}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/monica/data
        target: /var/www/html/storage
    networks:
      - monica
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.monica.rule: Host(`monica.${DOMAIN:?}`)
      traefik.http.routers.monica.entrypoints: websecure
      traefik.http.routers.monica.middlewares: ip-allowlist@docker
      traefik.http.services.monica.loadbalancer.server.port: 80
    depends_on:
      - monica-db
    restart: unless-stopped

  monica-db:
    image: mariadb:11
    container_name: monica-db
    profiles: [monica]
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: monica
      MYSQL_USER: ${MONICA_DB_USERNAME:?}
      MYSQL_PASSWORD: ${MONICA_DB_PASSWORD:?}
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/monica/mysql
        target: /var/lib/mysql
    networks:
      - monica
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  monica-backup:
    image: offen/docker-volume-backup:latest
    container_name: monica-backup
    profiles: [monica]
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/monica
        target: /backup/monica
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/monica
        target: /archive
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

networks:
  monica:
    name: monica
