services:
  ersatztv:
    image: jasongdove/ersatztv:latest-vaapi
    container_name: ersatztv
    profiles:
      - ersatztv
      - streaming
    environment:
      TZ: ${TZ:?}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/ersatztv
        target: /root/.local/share/ersatztv
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /media
        read_only: true
    # ports:
    #   - 8409:8409
    networks:
      - streaming
    labels:
      com.centurylinklabs.watchtower.enable: true
      docker-volume-backup.stop-during-backup: ersatztv
      traefik.enable: true
      traefik.http.routers.ersatztv.rule: Host(`tv.${DOMAIN:?}`)
      traefik.http.routers.ersatztv.entryPoints: websecure
    depends_on:
      - jellyfin
    restart: unless-stopped

  ersatztv-backup:
    image: offen/docker-volume-backup:v2
    container_name: ersatztv-backup
    profiles:
      - backup
      - ersatztv
      - streaming
    environment:
      EXEC_LABEL: ersatztv
      BACKUP_STOP_DURING_BACKUP_LABEL: ersatztv
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - type: bind
        source: ${APP_DATA_PATH:?}/ersatztv
        target: /backup/ersatztv
        read_only: true
      - type: bind
        source: ${BACKUP_DATA_PATH:?}/ersatztv
        target: /archive
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    network_mode: none
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
